### ISSUE TITLE
Remove parsers.csv_file

### ISSUE THREAD

**Issue by QuLogic** [phageParser/phageParser#115]
`CSVReader` wraps `csv` into an iterator and `CSVWriter` does some kind of buffering thing. But the reader could just use NumPy's `genfromtxt` or Pandas's `read_csv` or even the plain `csv`. Everything that uses `CSVWriter` also appears to write everything entirely, so it can just use `csv` directly.

**Comment by mbonsma** [comment]
I think these are all the instances where `CSVReader` and `CSVWriter` are used:

1.  [`find_accession.py`](https://github.com/phageParser/phageParser/blob/4e98ef123edacb6b33b255c3a1d6f7dc6ef1846a/parsers/find_accession.py) 
2. [`genome_extractor.py`](https://github.com/phageParser/phageParser/blob/4e98ef123edacb6b33b255c3a1d6f7dc6ef1846a/parsers/genome_extractor.py)

After deleting phage_file and phage_file_2_2_30, I don't think CSVWriter is needed at all. 

So the two parts to this issue:
1. Delete [`parsers/csv_file`].(https://github.com/phageParser/phageParser/blob/4e98ef123edacb6b33b255c3a1d6f7dc6ef1846a/parsers/csv_file.py)
2. Change `find_accession.py` and `genome_extractor.py` to use the `csv` module for the reader object.

**Comment by morrme** [comment]
looks like `genome_extractor` (now getgenomes) is ok, 

and `find_accession` would just need [this](https://github.com/phageParser/phageParser/blob/master/parsers/find_accession.py#L15) line changed to `csv.reader(blast_file, dialect=excel_tab)`

**Comment by mbonsma** [comment]
@morrme sounds good - there's also [this](https://github.com/phageParser/phageParser/blob/4e98ef123edacb6b33b255c3a1d6f7dc6ef1846a/parsers/genome_extractor.py#L16) line in `genome_extractor` as well as the import statements in both files.

**Comment by morrme** [comment]
@QuLogic @mbonsma I created PR #146 with my fix.
