### ISSUE TITLE
Add "accession" field to "restapi_anticrispr" model

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#119]
Once PR #118 is merged and we have a `models.py` script in the django-dev branch, we need to make a change to the `restapi_anticrispr` table. Right now it has two fields, `id` and `sequence`, and we should add a third field called `accession` to store the protein accession number. The schema is [here](https://github.com/phageParser/phageParser/blob/master/documentation/dbschema.svg).

An accession number looks something like `WP_043884810`.

Submit PRs to the `django-dev` branch, not master.

**Comment by morrme** [comment]
I would like to help, with mentoring, if possible. :)

**Comment by mbonsma** [comment]
Hi @morrme, that would be great! Myself or @cemyld can answer any questions about this one. 

The `models.py` file that needs to be modified is now in the repo [here](https://github.com/phageParser/phageParser/blob/django-dev/phageAPI/restapi/models.py) - it's the class `AntiCRISPR` that needs to be modified.

**Comment by morrme** [comment]
@mbonsma thanks! following the conventions of the file and the accession columns in other classes, I will use maxLength=50.  I have also reviewed the schema, and it doesn't look like you'll need foreign keys set up, correct?

**Comment by cemyld** [comment]
@morrme Hi, for this issue you don't need to set up foreign key. I think adding a CharField attribute similar to the one in Organism should suffice for now. You can open up a pull request when you're done and welcome!

**Comment by morrme** [comment]
@cemyld @mbonsma Thanks to both of you for the welcome and support. The PR has been submitted to the `django-dev` branch  :)

**Comment by mbonsma** [comment]
Woo! Done, thanks @morrme!
