### ISSUE TITLE
Populate database with Organism models

### ISSUE THREAD

**Issue by cemyld** [phageParser/phageParser#124]
A new method is needed for populating the organism table with models that include organism name and accession number. organism_name_update.py and acc2gb.py files are relevant in processing this information right now but the scripts have to be modified and merged into one which uses django's syntax to populate the API database. The created script can be added to django-dev branch.

**Comment by mbonsma** [comment]
This one was fixed in PR #125 right?

**Comment by cemyld** [comment]
@mbonsma Yes the PR #125 creates the script for populating the Organism model.
