### ISSUE TITLE
Script for matching spacers, repeats and organism for populating the api.

### ISSUE THREAD

**Issue by cemyld** [phageParser/phageParser#131]
After #120 #124 , a script is needed for matching spacer and repeat models so that SpacerRepeatPair objects can be created for adding to the database. For this script, jointable.py can be used for how to match the sequences. Two files needed for [`jointable.py`](https://github.com/phageParser/phageParser/blob/db9307afd88f6fd0b1c1d7b83e8a22c0bfa2133b/jointable.py) can be pulled remotely from web to utilize the most recent data.

While matching the Spacer and Repeat objects, the pairs can also be matched to the Organism objects by using the accession number for finding the specific organism and using the locus and order information for filling the order field in the OrganismSpacerRepeatPair.

In the OrganismSpacerRepeatPair model, genomic_start and genomic_end fields can be filled in by scraping the positions from web database similar to the [`extract_CRISPRdb.py`](https://github.com/phageParser/phageParser/blob/db9307afd88f6fd0b1c1d7b83e8a22c0bfa2133b/extract_CRISPRdb.py) script.

This issue has many highly interrelated parts therefore it is recommended for intermediate contributors. An example using django syntax for altering the models can be found in [`populate_organism.py`](https://github.com/phageParser/phageParser/blob/25063ec23cb9dfde24899244bea5ab67555457b8/phageAPI/populate_organism.py)

**Comment by mbonsma** [comment]
Solved in #150.
