### ISSUE TITLE
Make phageParser logo!

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#134]
PhageParser could really use a sweet logo! Someone with graphic design interest or experience, can we talk about what that might look like? I don't have many ideas myself, but maybe it could incorporate some DNA and a cute bacteria or virus.

**Comment by cemyld** [comment]
I made a couple of concept logos just to start it off.
![phageparser logos](https://cloud.githubusercontent.com/assets/6137137/25033532/befcf48a-20ac-11e7-8f83-5e1e6fbae7d7.png)

**Comment by mbonsma** [comment]
Yaayyyy I love these! @cemyld, awesome job!

**Comment by mbonsma** [comment]
I added "phageParser" in text below the blue one so we can have something to upload for the Global Sprint, but we can keep modifying it if we want! 

![phageparser 1](https://cloud.githubusercontent.com/assets/5651370/25201830/29f61c9e-2521-11e7-8874-bc79f5de280d.png)

**Comment by cemyld** [comment]
@mbonsma looks good! I got the DNA vector file online so there might be copyright issues for it but I can try making a clone of it from scratch. Apparently [there](http://www.freepik.com/free-vector/abstract-dna-symbol_764997.htm) is a free license for it with attribution but I'm not sure how exactly we credit the site for it.

**Comment by Abdelazeem-Elhabyan** [comment]
I think it needs to express CRISPR . You might open the double strand of DNA in the middle and attach small RNA that hybridise with one of DNA strand.

**Comment by mbonsma** [comment]
@Abdelazeem-Elhabyan I like it! Or maybe we could draw a Cas protein attached somewhere on the double-stranded DNA.
