### ISSUE TITLE
Combine acc2gb.py and fetchseq.py, putting db and rettype as arguments

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#137]
The scripts [`acc2gb.py`](https://github.com/phageParser/phageParser/blob/master/acc2gb.py) and [`fetchseq.py`](https://github.com/phageParser/phageParser/blob/master/fetchseq.py) do essentially the same thing: they use the Entrez system to download data from NCBI. 

We can combine them into a single, multi-purpose script by removing some of the hard-coded parameters and making them command line arguments. We'll keep the `acc2gb.py` script and delete `fetchseq.py` since it has fewer calls and @aays knows what they are. 

These are the changes that need to be made:

* [ ] Remove hardcoded `db` parameter on line 22 and make it a command line argument
* [ ] Remove hardcoded `rettype` parameter on line 33 and make it a command line argument
* [ ] Add parameter `retmode="text"` on line 33, same as in `fetchseq.py`.
* [ ] Include in the documentation what 'db' and 'rettype' mean and which arguments would be used in which situations. For now, these are the two we've been using:
* Case 1: `rettype = gbwithparts`, `db = nuccore` - downloads genbank file with metadata and fasta DNA sequence (i.e. for downloading bacterial genomes with metadata)
* Case 2: `rettype = fasta`, `db = protein` - downloads fasta file with protein sequence (i.e. for downloading antiCRISPR protein sequences for BLAST) 
* [ ] Delete `fetchseq.py`.

Submit a PR to the `master` branch when complete! If you have any questions at all, ping me or @aays and we'll get back to you ASAP.

**Comment by mbonsma** [comment]
Hi @morrme, definitely not just for first-timers! Go ahead!

**Comment by mbonsma** [comment]
Although I should check with @aays - have you done anything yet on this issue?

**Comment by morrme** [comment]
@mbonsma ok. if @aays gives the go-ahead, i've tried to do the steps on my end and the only one i'd need your help with is the docstring--properly defining the terms for your environment.

**Comment by mbonsma** [comment]
@morrme I'd say go ahead with the PR then, upon further thought I don't think @aays has started this yet. What do you have so far for the docstring?

**Comment by aays** [comment]
@morrme @mbonsma Easter weekend proved to be a bit busier than expected, and I indeed haven't gotten around to this yet - so I would say go for it!

**Comment by morrme** [comment]
@mbonsma thanks! i waited a while to see if any other first timer would want to take on the challenge, because i definitely appreciate your group for providing issues like these. 👍 

so as i'm not very familiar with the terminology, here's what I've been able to find via research: 

db  is NCBI database ID
another reference defines it as
> Target database about which to gather statistics. Value must be a valid Entrez database name. 


rettype is retrieval type. (or..."output file format"? ) 

The two examples you listed could be under an `Examples` heading.

**Comment by mbonsma** [comment]
@morrme, that looks good. How about this:

```
db: NCBI database ID, must be a valid Entrez database name
rettype: type of file to retrieve
retmode: output file format ('text' or 'xml')
```

And then, as you suggest, those two examples under `Examples`.

**Comment by morrme** [comment]
@mbonsma but `retmode` is not a parameter, as it is hard-coded to 'text', correct?

**Comment by mbonsma** [comment]
@morrme true, good point. We can leave that one out then.

**Comment by morrme** [comment]
@mbonsma @aays ready for review :smiley:
