### ISSUE TITLE
Analysis: distribution of CRISPR loci sizes

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#142]
*This issue is a work in progress - feel free to comment and if something is confusing please say so, but I will be fleshing this out more in the next few weeks!*

--------------------

An interesting question we can answer with available data is what the distribution of CRISPR locus sizes is. People often quote a minimum and maximum (~1 to ~500), but what is 'normal' given all the available data? 

Let's create a jupyter notebook that answers this question and produces some fun plots at the end. Here are roughly the steps:

1. [x] (Behind the scenes): Populate `organism`, `spacer`, `repeat`, `spacerrepeatpair` and `organismspacerrepeatpair` tables. The scripts to do this are [`populate_organism.py`](https://github.com/phageParser/phageParser/blob/django-dev/phageAPI/populate_organism.py), [`addspacerandrepeat.py`](https://github.com/phageParser/phageParser/blob/django-dev/phageAPI/addspacerandrepeat.py), and #131. Until we find somewhere to publicly host the database, this will have to be done locally - it's not a huge amount of data though. To skip this step, download the database file [here](http://phageparser.cemyildirim.fastmail.com/db.sqlite3).
2. [x] #166 - Make a function to return CRISPR loci from the database using the information in the `organismspacerrepeatpair` table. This should be a function that can be imported into another script and return a Python object that has all the repeats and spacers in order for that locus. 
3. [x] Count lengths of CRISPR loci using the function from the previous step. The length is the total number of spacers per locus. 
4. [x] Analysis and plots: calculate the average, median, and variance of locus length. Plot the full distribution of locus sizes, possibly cumulative.

**Comment by mbonsma** [comment]
Also fun with this information would be distribution of spacer lengths and repeat lengths.

**Comment by mbonsma** [comment]
@aays, I think you were working on this one?

**Comment by joelostblom** [comment]
I'll be working a bit on the the last bullet in about 2 hours, as soon as I'm done in lab. It won't be a function integrated into phageparser, more of an analyses with pandas (what I started yesterday), but maybe it can give some ideas for how to implement it later.

**Comment by mbonsma** [comment]
Done in [this demo notebook](https://github.com/phageParser/phageParser/blob/master/demos/Locus%20Number%20of%20Spacers%20Analysis.ipynb)
