### ISSUE TITLE
Create model for cas genes

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#147]
We want to store detected *cas* genes in the database so that we can determine CRISPR type based on them. Update [`models.py`](https://github.com/phageParser/phageParser/blob/django-dev/phageAPI/restapi/models.py) with a new jointable, `OrganismCas`, that has the following fields:

| Column:      | organism_id | accession | gene_id | start | end | evalue | 
| ---------------- | -------------- | ------------- | ------------ | -------- | --- | -------- |
| Description: | PK from `Organism` table | gene accession | gene name | cds start | cds end | e-value |

[//]: # (All of these fields except `organism_id` are output by the `PFAM_db.py` script. `gene_id` is in the `id` column, and `cds start` and `cds end` are the first and second numbers in the `cds` column respectively, separated by `. .`.)

**Comment by morrme** [comment]
I'd be up for this one as well, if you'd like to put a "gfb expiration date" on it :)

**Comment by mbonsma** [comment]
Go for it! (What does 'gfb expiration date' mean?)

**Comment by morrme** [comment]
in the last issue, you mentioned you'd let the good first bug label remain until friday, so i just called it an 'expiration' of sorts.

**Comment by mbonsma** [comment]
OHH gfb = good first bug, haha. I get it now! Well this one is a bit more essential than #165, so if you want to work on it right away go right ahead.

**Comment by mbonsma** [comment]
@morrme do you want to tackle this one? We're hoping to get started on #160 and #149 today which sort of depend on this one.

**Comment by mbonsma** [comment]
@joelostblom is going to take a look at this.

**Comment by morrme** [comment]
OK if he needs any support let me know, I can jump in this afternoon and complete it.

**Comment by mbonsma** [comment]
Fixed in PR #174
