### ISSUE TITLE
Fix link to image in README

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#153]
The CRISPR locus diagram in our README in the [about CRISPR](https://github.com/phageParser/phageParser/blob/master/README.md#about-the-crispr-system) section has a broken link - it's been moved to a [documentation](https://github.com/phageParser/phageParser/blob/master/documentation/CRISPR_locus_diagram.png) folder. We need to edit the README to fix the link!

**Comment by morrme** [comment]
I'll fix it!
