### ISSUE TITLE
Create .travis.yaml file now that Travis is enabled!

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#159]
Something like the example [here](https://docs.travis-ci.com/user/languages/python/).

**Comment by djmitche** [comment]
I can add this, but I'm not sure what to do in Travis without a test suite (#18)..

I suppose just running `python setup.py install` would be sufficient. It seems that is failing right now (iPython==6.0.0 isn't avilable).

Is there a simple, quick way to run all of the scripts?  That might at least help to suss out some basic Python-2/3 issues.

**Comment by cemyld** [comment]
@djmitche for now, the testing will mostly be used for checking the api. I've added two sample tests for creating or deleting models in restapi django app that is checked with travis for now. If you have any ideas for creating tests for checking the restful api that would be great!

**Comment by djmitche** [comment]
ok -- so do the scripts not matter anymore, now that there's an API?

**Comment by mbonsma** [comment]
@djmitche some of them won't be useful anymore, but mostly the scripts are still important for doing updates and adding analyses.

**Comment by mbonsma** [comment]
Can we close this?

**Comment by djmitche** [comment]
Yes -- now that I realize that the "interesting" stuff is the API, while the scripts are just for maintenance.  So if those aren't python-3 compatible it's not a big deal.

**Comment by mbonsma** [comment]
Ok cool, agreed.
