### ISSUE TITLE
Convert to Python 3

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#164]
I think the easiest way to do this (please correct me if I'm wrong) is to try running scripts in a Python 3 virtualenv (see [Installation](https://github.com/phageParser/phageParser/blob/master/README.md#installation)), and fix whatever breaks. 

Alternatively, if someone knows how, we can set up Travis with some tests and automate it that way. 

Here is a starter list of scripts that haven't been tested:
* [ ] [acc2gb.py](https://github.com/phageParser/phageParser/blob/master/acc2gb.py)
* [ ] [CRIPSRfinder.py](https://github.com/phageParser/phageParser/blob/master/CRISPRfinder.py)
* [ ] [cleanPhages.py](https://github.com/phageParser/phageParser/blob/master/cleanPhages.py)

**Comment by QuLogic** [comment]
Are you keeping Python 2 support?

**Comment by djmitche** [comment]
I'd suggest *not* keeping Python 2 support, since as I understand it this is not used as a library that must interact with other tools.  Every system has Python 3 installed these days, so while user upgrades might require making a new (Python 3) virtualenv, that's a one-time cost.

**Comment by djmitche** [comment]
I don't know if this is done yet, without testing those scripts..
