### ISSUE TITLE
Rename capitalized scripts so that GitHub sorts nicely

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#165]
In the main repo view, GitHub sorts all the files alphabetically but also apparently sorts by first letter capitalized. We should un-capitalize the scripts that are showing up at the top so that files like README and CONTRIBUTING are correctly placed near the top. 

The scripts in question:
* [ ] [BLAST_loop.py](https://github.com/phageParser/phageParser/blob/master/BLAST_loop.py)
* [ ] [CRISPR_db_parser.py](https://github.com/phageParser/phageParser/blob/master/CRISPR_db_parser.py)
* [ ] [CRISPRfinder.py ](https://github.com/phageParser/phageParser/blob/master/CRISPRfinder.py)
* [ ] [PFAM_db.py](https://github.com/phageParser/phageParser/blob/master/PFAM_db.py)

In all these cases, I'd say just rename to make the whole thing lowercase.

Submit PR to the master branch.

![image](https://cloud.githubusercontent.com/assets/5651370/26646281/fdd90a82-4608-11e7-8e63-4ca4b7e7b818.png)

**Comment by morrme** [comment]
@mbonsma I don't want to take all of your good first bug issues if you'd like to reserve them for new contributors, but feel free to ping me if you need it done!!!! ❤️

**Comment by mbonsma** [comment]
@morrme thanks!! Let's leave this one until the end of Friday, and if no one comes for it by then, it's all yours!

**Comment by morrme** [comment]
@mbonsma i really want to take on one of the script tasks, so this is probably my way of procrastinating lol

**Comment by mbonsma** [comment]
@morrme Oh I know the feeling - tidying is so much more appealing than taking on a whole new chunk...

But there are some super cool script ones you could do! Like #149 or #166!

**Comment by morrme** [comment]
i'm so scared to admit this but i've wanted #122 like forever .

**Comment by QuLogic** [comment]
Or put them all in a subdirectory?

**Comment by mbonsma** [comment]
Yeah maybe that's better? Like a 'scripts' folder?

**Comment by QuLogic** [comment]
Depends if you're making a package after? Probably should follow some sort of convention along those lines.

**Comment by morrme** [comment]
Good point.

**Comment by wgma00** [comment]
Hello, I can pick this issue.
