### ISSUE TITLE
Function to return CRISPR loci object from database

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#166]
It turns out that a reconstruction of a CRISPR locus will be a handy object to have for various analyses. We should make a function that does this that can be plugged in other places. 

--------

In the current database schema, the table `organismspacerrepeatpair` links up organisms and which spacers and repeats they have in what order. (Here's the [schema](https://github.com/phageParser/phageParser/blob/master/documentation/dbschema.svg)). The fields in `organismspacerrepeatpair` are:

| id  | order   | genomic_start | genomic_end | organism_id | repeat_id | spacer_id | 
| ---------------- | -------------- | ------------- | ------------ | -------- | ---------- | ----------- |

The `order` column indicates where in the CRISPR locus each spacer-repeat pair comes from. A single organism can have more than one locus: it will be a bit tricky, but using the `genomic_start` and `genomic_end` field we can separate loci if pairs are separated by more than the length of spacer + repeat. @cemyld should have some advice for how to deal with this. `spacer_id` and `repeat_id` are foreign keys for the `spacer` and `repeat` tables. 

A CRISPR locus looks like [this](https://raw.githubusercontent.com/phageParser/phageParser/master/documentation/CRISPR_locus_diagram.png) - spacers are sandwiched between repeats. 

Make a function to return CRISPR loci from the database using the information in the `organismspacerrepeatpair` table. It should probably take as an input a bacterial accession number and return a Python object that has all the repeats and spacers in order for that locus. I'm not sure what the best structure would be for this object, we can discuss.

**Comment by cemyld** [comment]
This function can be written as an additional field in the organism serializer to get the loci as lists of organismspacerrepeatpairs. An example function as a field can be found in `serializers.py`

**Comment by cemyld** [comment]
Fixed with #221
