### ISSUE TITLE
Remove hardcoded inputs in blast_loop.py

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#189]
These two scripts do basically the same thing:

* https://github.com/phageParser/phageParser/blob/master/blast_loop.py
* https://github.com/phageParser/phageParser/blob/master/blast_spacer_to_host_genome.py

We can probably combine them and change hardcoded inputs (settings, folders, etc) to options, similar to what we did in #137.

**Comment by mbonsma** [comment]
Some BLAST use cases:

1. Blast spacers against host genome - `query=spacer_seq, subject=bac_genome, task = "blastn" `
2. Blast spacers against phage databae - `query=spacer_seq, db="phagedb", task = "blastn"`
3. Blast anticrispr genes - `cmd = 'tblastn', query=anti_crispr_seq, subject=bac_genome`

Roughly, these are the blast parameters that should be required:
```
query
subject / db # subject sequence or blast database
outfmt # output format 
task / cmd # i.e. 'tblastn, blastn'       
evalue # expect value cutoff, i.e. 1 or 10                     
```

And these should be optional:
```
num_descriptions 
num_alignments
dust 
reward 
penalty  
out 
```

**Comment by mbonsma** [comment]
Also, maybe we should go for gold and also combine [`anticrisprblast`](https://github.com/phageParser/phageParser/blob/master/anticrisprblast.py) as well.

**Comment by mbonsma** [comment]
And look for any other loose scripts that are doing special cases, and specify each special case as an example in the documentation for the script.

**Comment by aays** [comment]
I can take a stab at this!
