### ISSUE TITLE
Figure out what exactly we should be downloading from NCBI in terms of bacterial and archaeal genomes

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#199]
We want all published genomes of bacteria and archaea, but unfortunately NCBI's standards and file system are not easy to understand. We've been skirting this by just using the data from a different [CRISPR database](http://crispr.i2bc.paris-saclay.fr/), but eventually we'd like to not rely on them and just download directly from NCBI so that we can update whenever we want. 

If we could get a list of accession numbers for all the available bacteria and archaea, that would be great. Do we want all the `NC_` accessions? What about `NZ_`? What's the difference? Is there overlap?

Anyone who knows about this and/or feels like doing some reading up on NCBI is very welcome to help us here! 

Feeds into #196.

**Comment by mbonsma** [comment]
For example, you could get all the `NC_` accessions for bacteria by pasting `NC_000000:NC_999999[ACCN] AND "bacteria"[Filter] ` into the NCBI search bar, downloading a ginormous fasta file, and parsing it for just the headers with the accessions.

**Comment by mbonsma** [comment]
Some resources: 
* [NCBI documentation on sequence IDs](https://www.ncbi.nlm.nih.gov/genbank/sequenceids/)
* [NCBI list of accession numbers](https://www.ncbi.nlm.nih.gov/Sequin/acc.html)

**Comment by mbonsma** [comment]
[Entrez GUI notes](https://www.ncbi.nlm.nih.gov/books/NBK44863/)

**Comment by aays** [comment]
@mbonsma I found [this link](https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/) while trawling around NCBI's site - the answer to question 1 in particular seems relevant? I'm unsure of the actual file format it returns, but I'd hazard a guess it's in either fastq or bam format, both of which can be easily converted to fasta if need be.

**Comment by mbonsma** [comment]
@aays Yeah that looks great! I think I'll try the steps in question 1 and see if it does the trick. It's not a command line solution, but it's hopefully something that doesn't need to happen very often.

**Comment by mbonsma** [comment]
So it kind of worked, you get all the assemblies and a file called `md5checksums.txt` that has all the accessions. They're assembly accessions and not the Refseq accessions though - i.e. `GCF_000007325.1_ASM732v1`

**Comment by aays** [comment]
@mbonsma Darn, that's not good! I wonder if there's a way to find corresponding RefSeq accessions from that file? But that does seem like a bit of a convoluted solution, and it would be idea to query RefSeq itself in a similar fashion. Also, are the assemblies in any kind of usable format?

That being said, I tried using similar filtering on RefSeq and I think I'm on to something here. If we head to https://www.ncbi.nlm.nih.gov/nuccore/?term=all[filter] (https://www.ncbi.nlm.nih.gov/refseq/?term=all[filter] also works, but ends up redirecting to Nucleotide - should be fine I think?) and enter the following in the filter field on the right hand side:

```sql
all[filter] AND srcdb_refseq[PROP] AND bacteria[filter] OR archaea[filter]
```

it seems to return genomic data. The problem is that these are mostly in the form of independent contigs, and dealing with those would be a separate issue entirely, I'd think.

**Comment by mbonsma** [comment]
We could maybe use this [`ncbi-genome-download`](https://github.com/kblin/ncbi-genome-download) program and then maybe just write our own for our specific use case. 

To get all bacterial genbank files, which is the current format we're using, this search works in the [assembly](https://www.ncbi.nlm.nih.gov/assembly) site:

```
all[filter] AND (bacteria[filter] AND latest[filter] AND all[filter] NOT anomalous[filter]) AND ("latest refseq"[filter] AND "complete genome"[filter] AND all[filter] NOT partial[filter])
```

So we'd just need to find the appropriate keywords to do that with `ncbi-genome-download`.

**Comment by aays** [comment]
Having gone through the documentations, this looks like our best bet to me! It would only download complete bacterial genomes (and not contigs or scaffolds) and return GenBank + FASTA files. Could also be appended with a `--parallel n` argument before `bacteria` to speed up the process.

```
ncbi-genome-download --assembly-level complete --format genbank fasta bacteria
```

**Comment by mbonsma** [comment]
It seems like every time I look for something on NCBI I find a different route. Anyway, I found this [genome browser page](https://www.ncbi.nlm.nih.gov/genome/browse/?report=2) from which you can download a summary file for all prokaryotes, say. The summary file has assembly accessions, chromosome accessions, and ftp links:

```
Chlamydomonas reinhardtii	CC-503 cw92 mt+	SAMN02953692 	PRJNA12260	Plants	Green Algae	120.405	61.9512	GCA_000002595.2 	mitochondrion MT:NC_001638.1/U03843.1; chloroplast Pltd:NC_005353.1/BK000554.2	ABCN01	1558	14488	14489	2007/08/03	2014/08/06	Scaffold	ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/595/GCF_000002595.1_v3.0	ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/002/595/GCA_000002595.2_v3.0

```

**Comment by aays** [comment]
@mbonsma Oh hey, it's my model organism! That looks pretty awesome. I suppose one could write a script to iterate through downloaded summary files, pull ftp links, and download from those? Otherwise, I think the `ncbi-genome-download` program is also a solid option if integrated with `subprocess` or something along those lines.

**Comment by mbonsma** [comment]
@aays oh neat! It was just the first one in the text file! 

Yeah, I was thinking we could stick to the full genomes by pulling out the replicon sequence accession numbers and downloading those. Maybe the ftp links would also be fine, but if we use the accessions we can just use `acc2gb.py`.

**Comment by mbonsma** [comment]
This ftp site (ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/IDS/Bacteria.ids) has files for various groups of organisms in a very convenient table that we can parse into a list of accessions with [collect_accessions.py](https://github.com/phageParser/phageParser/blob/2bbde84bbd0987ef4793d562d7e8746c683f8ccf/parserscripts/collect_accessions.py). Thanks to @thisisjaid for finding this and making the script!
