### ISSUE TITLE
Remove hardcoded inputs and outputs in collect_accessions.py

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#244]
`collect_accessions.py` (PR #243) has file names hardcoded in the input and output. It should be modified to:

* [ ] accept the input and output filenames as command line arguments, and
* [ ] have a docstring that explains what the arguments are and what the script does. 

See [`crispr_finder.py`](https://github.com/phageParser/phageParser/blob/master/parserscripts/crisprfinder.py) for an example of a docstring (top rows in triple quotes) and accepting arguments.

**Comment by thegreyelephant** [comment]
Hi - can I work on this bug as part of Hacktoberfest?!

**Comment by mbonsma** [comment]
@thegreyelephant sure, please do!

**Comment by thisisjaid** [comment]
Sorry I had kind of already addressed this as part of the Pandas rewrite PR :/

**Comment by thegreyelephant** [comment]
@thisisjaid Oh - OK. No worries, I'll look for another beginner bug!

**Comment by QuLogic** [comment]
@mbonsma So close this?
