### ISSUE TITLE
Help wanted about how to find the relationship of phage-bacterium 

### ISSUE THREAD

**Issue by FenghuJ** [phageParser/phageParser#271]
Hi，
I am working on constructing bacteria-phage network with metagenomics data.Now I have extracted the spacer sequences and direct repeat sequences with Crass .But I am quite confused about how to use phageParse to help me construct the network , which script should I use  to get
1、the phage  species
2、the  bacterial species 
3、the interaction between phage and bacteria
Could you please give me some advice ,I would be grateful .Thank you~

**Comment by mbonsma** [comment]
Hi @FenghuJ, I just replied to your email! In the next week or so I also hope to update that portion of the pipeline so that it's clear what to do.
