### ISSUE TITLE
Convert phage identifier headers into phage names

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#29]
### Motivation

Given a list of phage identifiers from different databases (currently three) and different formats, it would be good to have a standardized list of just the phage names to make it easier to understand the results. As it is right now, the "phage name" is just the header from the phage genome file, and these differ depending on where we got the phage from.

---
### The function

This function should accept a header string as input and return just the name portion of the header. Below are three examples of the kinds of headers we are currently encountering.

**Optional fanciness:**
Ideally, this could be generalized to more and different databases, and so a smart regular expression matching system may be required to deal with unknown formats. Perhaps the user could be asked to specify the location or format of the phage name in the header string.

**Examples:**
Currently, data is being used from three databases:
1. [European Nucleotide Archive phage database](http://www.ebi.ac.uk/genomes/phage.html)

Examples:
> ENA|AP013478|AP013478.1 Uncultured Mediterranean phage uvMED DNA, complete genome, group G18, isolate: uvMED-CGR-U-MedDCM-OCT-S26-C62. [29-AUG-2014]
> ENA|AP013029|AP013029.1 Bacillus phage phiNIT1 DNA, complete genome. [21-NOV-2014]

The name of the first example is "Uncultured Mediterranean phage uvMED", the second is "Bacillus phage phiNIT1"
1. [Mycobacteriophage database](http://phagesdb.org/)

Examples:
> Vix Complete Sequence, 50963 bp including 10 bp 3' overhang (CGGGTGGTAA), Cluster A3
> JoeDirt Final Sequence, 74914 bp including 10 bp 3' overhang (TCGAACGGCC), Cluster L1

The phages in this database have strange names ("Vix" and "JoeDirt" in these examples). See the [naming rules](http://phagesdb.org/namerules/) for an explanation. 

Since these strangely-named phages are all mycobacteriophages, it would be good if "Mycobacteriophage" could be added as a prefix to the name. (i.e. "Vix" would become "Mycobacteriophage Vix".)
1. [NCBI virus database](http://www.ncbi.nlm.nih.gov/genome/viruses/)

Examples:
> gi|526118413|ref|NC_021856.1| Bacillus phage phiNIT1 DNA, complete genome
> gi|345461275|ref|NC_015941.1| Bat picornavirus 2, complete genome

**Comment by mbonsma** [comment]
I'm going to take a crack at this one. It's just kind of gunky but it should be straightforward.

**Comment by mbonsma** [comment]
I think this should be rolled into `orderByExpect` so we don't have to create a bajillion files at each step. I'll make it separate for starters, but basically it will involve re-writing the CSV to clean up the phage name section. The second column that contains the string `"gi|399498678|ref|NC_018285.1| Streptococcus phage YMC-2011,"` in the example below would be split into two columns, one with the accession number `NC_018285` and one with the name `Streptococcus phage YMC-2011`.

This means the function `getAccession(name)` from issue #2 should be used to insert the accession number for those phages that are from PhagesDB.  

```
Query,Name,Length,Score,Expect,QueryStart,QueryEnd,SubjectStart,SubjectEnd

2.17,"gi|399498678|ref|NC_018285.1| Streptococcus phage YMC-2011, ",40758,34.2,0.4,33,49,29387,29403
```

**Comment by mbonsma** [comment]
The function `clean_phages.py` is where this should be added - it basically replaces `orderByExpect.py`.

**Comment by Maritimesailor** [comment]
I'll look into this issue

**Comment by mbonsma** [comment]
@Maritimesailor, we can chat about this if you like. A few people did some stuff already, so it's more about modifying existing scripts than making an entirely new one. Probably one of the more difficult "good first bugs", so feel free to ask for clarification.

**Comment by Maritimesailor** [comment]
I am right now looking at the code and I will get back you.

**Comment by Maritimesailor** [comment]
Well what needs to be modified?

**Comment by mbonsma** [comment]
The function [clean_phages.py](https://github.com/goyalsid/phageParser/blob/master/cleanPhages.py) already does this for two of the three databases, but not for the phagesDB database. The `clean_phages.py` function runs on CSV files created by `filterByExpect.py` or one of its variants (in progress). 

I uploaded some example output files from this process under [data/output](https://github.com/goyalsid/phageParser/tree/master/data/output). So what needs to be added is a step in the [split_name](https://github.com/goyalsid/phageParser/blob/master/cleanPhages.py#L30) function to deal with the missing database format, which is this:

2. [Mycobacteriophage database](http://phagesdb.org/)

Examples:
\> Vix Complete Sequence, 50963 bp including 10 bp 3' overhang (CGGGTGGTAA), Cluster A3
\> JoeDirt Final Sequence, 74914 bp including 10 bp 3' overhang (TCGAACGGCC), Cluster L1

The phages in this database have strange names ("Vix" and "JoeDirt" in these examples). See the [naming rules](http://phagesdb.org/namerules/) for an explanation. 

Since these strangely-named phages are all mycobacteriophages, it would be good if "Mycobacteriophage" could be added as a prefix to the name. (i.e. "Vix" would become "Mycobacteriophage Vix".)

**Comment by VanitaW** [comment]
Hi!  I am a newbie with only class project experience in python.  Is this still open to work on?

**Comment by mbonsma** [comment]
Hello @VanitaW and welcome! I'm just looking through the comments and work on here and it looks like this one might actually be finished. I just added another `good first bug` though if you're interested in that one: #244.

**Comment by VanitaW** [comment]
Thank you.
