### ISSUE TITLE
Script to BLAST spacers against host genome

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#60]
### Motivation

Research has suggested that there may be cases when CRISPR systems are used for something besides immunity to foreign DNA - perhaps they could be regulating the host genome, or they might simply be inactive. A clue that one of these things might be happening is if there are spacers that come from their own host genome. To this end, we need functions to (A) BLAST spacers against the host genome and (B) analyze the BLAST output. The first function is described in this issue. The second is described in issue #62. 

---
### The Function

**Input:**
- List of spacers in the genome. Example files in [data/spacers](https://github.com/goyalsid/phageParser/tree/master/data/spacers) contain a list of all the CRISPR spacers identified for that organism. The organism is identified by an NCBI accession number, which is the name of the file.
- Accession number of organism (title of file containing list of spacers) - i.e. NC_000853.
- _Optional time window `t` (in months) - if date downloaded is more than `t` months ago, re-download from NCBI._ - moved to Issue #74
- Optional BLAST parameters - could be left as default for first iteration.

**The function should do the following:**
- _Check if the genome of the organism has already been downloaded - i.e., is it in `phageParser/data/prokaryote_genomes`?_ - moved to Issue #74
- _If it hasn't been downloaded OR if it is more than `t` months out of date, fetch the genome from NCBI using [acc2gb.py](https://github.com/goyalsid/phageParser/blob/master/acc2gb.py)._ - moved to Issue #74
- BLAST the list of spacers for that organism against the genome using [BioPython's standalone BLAST wrapper](http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc89). Note: you will need to install [BLAST+](http://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=Download) locally. The script [BLAST_loop.py](https://github.com/goyalsid/phageParser/blob/master/BLAST_loop.py) could be used as a template for this process. The main difference between the two is that in this version the subject sequence is a single genome, not a database.

**Output:**
- XML file with BLAST output. 

Note: The default parameters may need some fiddling - the defaults in BLAST_loop.py are a good start.

**Comment by mbonsma** [comment]
@lwgray will be taking a look at this issue!

**Comment by lwgray** [comment]
I have made some progress on this issue... I will submit a pull request so we can discuss this more
1.  I have set up the script to check for the presence of the spacer file based on accession_id
2.  I have set up the script to check if the geneome file is current based on user specified parameter

A few import tasks need to finish.
1.  Fetch file is not downloaded or not up-to-date
2.  Perform Spacer Blast
3.  Add default blast parameters
4.  Convert file to command-line tool
5.  Add unit-tests
6.  Choose more appropriate file name

**Comment by mbonsma** [comment]
@lwgray, I have a suggestion for a slight change of plan - I'm thinking about future scripts that will also need to check if the genome file is current, so what do you think about splitting this into two (or even three) functions?

One will do what you've already done:

**Comment by lwgray** [comment]
It might be best to write a class so that other scripts can call the first set of functions

**Comment by mbonsma** [comment]
Good call. I'll revise this issue and make a new one to reflect that.

**Comment by lwgray** [comment]
@mbonsma 
Can we set up a hangout sometime this week to discuss the issue #60 again?

**Comment by mbonsma** [comment]
@lwgray, is next week Tuesday (afternoon) an option? This week is a bit crazy for me unfortunately.

**Comment by lwgray** [comment]
Sure no worries, whenever you are free... i am just procrastinating  thus
wirking on phageparser i stead of my research.

cheers
larry

**Comment by mbonsma** [comment]
`blast.py` (#201) is now a general-purpose blast script.
